export const sortList = [
  {
    title: '姓名',
    dataIndex: 'name',
    // width: 116,
    // fixed: 'left',
    // checked: true,
    // disabled: false,
    // ellipsis: 1,
  },
  {
    title: '年龄',
    dataIndex: 'age',
    // width: 116,
    // align: 'right',
    // checked: true,
    // disabled: false,
    // ellipsis: 1,
  },
  {
    title: '住址',
    dataIndex: 'address',
    // width: 250,
    // checked: false,
    // disabled: false,
    // ellipsis: 1,
  },
  {
    title: '邮件',
    dataIndex: 'email',
    // width: 160,
    // checked: false,
    // disabled: false,
    // ellipsis: 1,
  },
  {
    title: '毕业院校',
    dataIndex: 'school',
    // width: 160,
    // checked: true,
    // disabled: false,
  },
  {
    title: '学位',
    dataIndex: 'degree',
    // width: 160,
    // checked: true,
    // disabled: false,
    // ellipsis: 1,
  },
  {
    title: '身份证号',
    dataIndex: 'id',
    // width: 200,
    // fixed: 'right',
    // align: 'right',
    // checked: true,
    // disabled: false,
    // ellipsis: 1,
  },
];
